---
title: "Rendu"
format: html
---

## Attention, cette page est en cours de rédaction !

Les profs sont encore en train de se mettre d’accord sur ce qui est demandé pour le projet final. Pour ceux qui voudraient commencer, je mets déjà quelques éléments comme le jeu de données pour que vous puissiez commencer à l’intégrer dans GeoServer.

## Résumé des éléments demandés

_En cours de rédaction_

- Un GeoServer qui sert au moins une couche de points requêtable (deals) et une couche de polygones (pays). Vous pouvez (et devriez certainement) servir plus de couches.

- Une page qui contient une carte OpenLayers et une carte Leaflet (ou plusieurs pages web si vous êtes très chauds).

- Le code final build (`npm run build`) et visible sur le serveur de production `localhost:80`.

- Le code mis en ligne sur un projet GitHub (on ne demande pas de branch, etc. mais juste d’avoir le code final sur GitHub).

### Sur la carte OpenLayers

- Un menu pour choisir entre deux fonds de carte (utilisez des radio buttons).

- Un menu qui permet d’afficher / masquer les autres couches de la carte.

- Un menu qui vous permet de filtrer une des couches (probablement deals).

## Le jeu de données

Pour ceux qui veulent commencer à importer les couches dans GeoServer.

**Si vous voulez utiliser un autre jeu de données, sur un truc qui vous intéresse plus, vous pouvez ! Tant qu’on a tous les éléments demandés dans l’évaluation, peu importe la donnée.**

[land_matrix_agri](/data/land_matrix/land_matrix_agri.gpkg)

